apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: branchprotector
spec:
  schedule: {{ .Values.branchprotector.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
{{- if .Values.branchprotector.tolerations }}
          tolerations:
{{ toYaml .Values.branchprotector.tolerations | indent 12 }}
{{- end }}
          containers:
          - name: branchprotector
            image: {{ quote .Values.branchprotector.image }}
            args:
            - --config-path=/etc/config/config.yaml
            - --job-config-path=/etc/job-config
            - --github-endpoint=http://ghproxy
            - --github-endpoint=https://api.github.com
            - --github-token-path=/etc/github/oauth
            - --confirm=true
            - --github-endpoint=http://ghproxy
            volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: job-config
              mountPath: /etc/job-config
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: {{ .Values.secrets.githubToken }}
          - name: config
            configMap:
              name: config
          - name: job-config
            configMap:
              name: job-config