apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crier
  labels:
    app: crier
spec:
  replicas: {{ .Values.crier.replicas }}
  template:
    metadata:
      labels:
        app: crier
    spec:
      serviceAccountName: crier
      terminationGracePeriodSeconds: 30
      containers:
      - name: crier
        image: {{ .Values.crier.image }}
        args:
        - --github-workers=1
        - --slack-workers=1
        - --slack-token-file=/etc/slack/token
#        - --report-agent=knative-build
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --github-endpoint=http://ghproxy
#        - --github-endpoint=https://api.github.com
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: slack
          mountPath: /etc/slack
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: oauth
        secret:
          secretName: {{ .Values.secrets.oauthToken }}
      - name: slack
        secret:
          secretName: {{ .Values.secrets.slackToken }}