apiVersion: apps/v1
kind: Deployment
metadata:
  name: crier
  labels:
    app: crier
spec:
  replicas: {{ .Values.crier.replicas }}
  selector:
    matchLabels:
      app: crier
  template:
    metadata:
      labels:
        app: crier
    spec:
      serviceAccountName: crier
      terminationGracePeriodSeconds: 30
{{- if .Values.crier.tolerations }}
      tolerations:
{{ toYaml .Values.crier.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: crier
        image: {{ .Values.crier.image }}
        args:
        - --github-workers=10
        - --blob-storage-workers=10
{{ if .Values.secrets.slackToken }}
        - --slack-workers=1
        - --slack-token-file=/etc/slack/token
{{ end }}
#        - --report-agent=knative-build
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-token-path=/etc/github/oauth
        - --gcs-credentials-file=/etc/gcs-credentials/service-account.json
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: gcs-credentials
          mountPath: /etc/gcs-credentials
          readOnly: true
{{ if .Values.secrets.slackToken }}
        - name: slack
          mountPath: /etc/slack
          readOnly: true
{{ end }}
      volumes:
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: oauth
        secret:
          secretName: {{ .Values.secrets.githubToken }}
      - name: gcs-credentials
        secret:
          secretName: {{ .Values.secrets.bucketGcsCredentials }}
{{ if .Values.secrets.slackToken }}
      - name: slack
        secret:
          secretName: {{ .Values.secrets.slackToken }}
{{ end }}