kind: ServiceAccount
apiVersion: v1
metadata:
  name: "crier"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crier
rules:
- apiGroups:
    - "prow.k8s.io"
  resources:
    - "prowjobs"
  verbs:
    - "get"
    - "watch"
    - "list"
    - "patch"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crier
  namespace: {{ .Values.podNamespace }}
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
    - "events"
  verbs:
    - "get"
    - "list"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: crier-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "crier"
subjects:
- kind: ServiceAccount
  name: "crier"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: crier-namespaced
  namespace: {{ .Values.podNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "crier"
subjects:
- kind: ServiceAccount
  name: "crier"
  namespace: {{ .Release.Namespace }}