---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deck
  labels:
    app: deck
spec:
  replicas: {{ .Values.deck.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: deck
    spec:
      serviceAccountName: "deck"
      terminationGracePeriodSeconds: 30
{{- if .Values.deck.tolerations }}
      tolerations:
{{ toYaml .Values.deck.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: deck
        image: {{ quote .Values.deck.image }}
        args:
        - --config-path=/etc/config/config.yaml
        - --tide-url=http://tide/
        - --hook-url=http://hook:8888/plugin-help
        - --redirect-http-to={{ quote .Values.deck.host }}
        - --oauth-url=/github-login
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --spyglass=true
        - --rerun-creates-job
        - --github-token-path=/etc/github/oauth
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-oauth-config-file=/etc/githuboauth/secret
        - --cookie-secret=/etc/cookie/secret
        - --plugin-config=/etc/plugins/plugins.yaml
        - --gcs-credentials-file=/etc/gcscredentials/service-account.json
        ports:
          - name: http
            containerPort: 8080
          - name: metrics
            containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: oauth-config
          mountPath: /etc/githuboauth
          readOnly: true
        - name: oauth-token
          mountPath: /etc/github
          readOnly: true
        - name: gcs-credentials
          mountPath: /etc/gcscredentials
          readOnly: true
        - name: cookie-secret
          mountPath: /etc/cookie
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 600
      volumes:
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: oauth-config
        secret:
            secretName: {{ .Values.secrets.oauthConfig }}
      - name: oauth-token
        secret:
            secretName: {{ .Values.secrets.githubToken }}
      - name: gcs-credentials
        secret:
            secretName: {{ .Values.secrets.bucketGcsCredentials }}
      - name: cookie-secret
        secret:
            secretName: deck-cookie
      - name: plugins
        configMap:
          name: plugins