apiVersion: v1
kind: Secret
metadata:
  name: deck-cookie
  annotations:
# https://github.com/helm/helm/issues/3053#issuecomment-518403351
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  secret: {{ randAlpha 32 | b64enc | b64enc | quote }} 