apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghproxy
  name: ghproxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8888
  - name: metrics
    port: 9090
  selector:
    app: ghproxy
  type: ClusterIP