apiVersion: v1
kind: Secret
metadata:
  name: hmac-token
  annotations:
# https://github.com/helm/helm/issues/3053#issuecomment-518403351
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  hmac: {{ randAlphaNum 20 | b64enc | quote }}