---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hook
  labels:
    app: hook
spec:
  replicas: {{ .Values.hook.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hook
    spec:
      serviceAccountName: "hook"
      terminationGracePeriodSeconds: 180
      containers:
      - name: hook
        image: {{ quote .Values.hook.image }}
        imagePullPolicy: IfNotPresent
        args:
{{ if .Values.secrets.slackToken }}
        - --slack-token-file=/etc/slack/token
{{ end }}
        - --dry-run=false
        - --config-path=/etc/config/config.yaml
        - --github-endpoint=http://ghproxy
#        - --github-endpoint=https://api.github.com
        - --job-config-path=/etc/job-config
        ports:
          - name: http
            containerPort: 8888
          - name: metrics
            containerPort: 9090
        volumeMounts:
{{ if .Values.secrets.slackToken }}
        - name: slack
          mountPath: /etc/slack
          readOnly: true
{{ end }}
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 600
      volumes:
{{ if .Values.secrets.slackToken }}
      - name: slack
        secret:
          secretName: {{ .Values.secrets.slackToken }}
{{ end }}
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: {{ .Values.secrets.githubToken }}
      - name: config
        configMap:
          name: config
      - name: plugins
        configMap:
          name: plugins
      - name: job-config
        configMap:
          name: job-config