apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: label-sync
spec:
  schedule: {{ .Values.labelsync.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: label-sync
    spec:
      template:
        spec:
{{- if .Values.labelsync.tolerations }}
          tolerations:
{{ toYaml .Values.labelsync.tolerations | indent 12 }}
{{- end }}
          containers:
            - name: label-sync
              image: {{ quote .Values.labelsync.image }}
              args:
              - --config=/etc/config/labels.yaml
              - --confirm=true
              - --orgs={{ .Values.github.org }}
              - --token=/etc/github/oauth
              volumeMounts:
              - name: oauth
                mountPath: /etc/github
                readOnly: true
              - name: config
                mountPath: /etc/config
                readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: {{ .Values.secrets.githubToken }}
          - name: config
            configMap:
              name: label-config