apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: needs-rebase
  labels:
    app: needs-rebase
spec:
  replicas: {{ .Values.needsrebase.replicas }}
  template:
    metadata:
      labels:
        app: needs-rebase
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: needs-rebase
        image: {{ quote .Values.needsrebase.image}}
        imagePullPolicy: IfNotPresent
        args:
        - --dry-run=false
        - --github-endpoint=http://ghproxy
#        - --github-endpoint=https://api.github.com
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: {{ .Values.secrets.githubToken }}
      - name: plugins
        configMap:
          name: plugins