{{- if .Values.needsRetitle.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: needs-retitle
spec:
  selector:
    app: needs-retitle
  ports:
  - port: 80
    name: http
    targetPort: 8888
  type: ClusterIP
{{- end }}