---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prow-controller-manager
  labels:
    app: prow-controller-manager
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prow-controller-manager
  template:
    metadata:
      labels:
        app: prow-controller-manager
    spec:
      serviceAccountName: "prow-controller-manager"
{{- if .Values.prowcontrollermanager.tolerations }}
      tolerations:
{{ toYaml .Values.prowcontrollermanager.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: prow-controller-manager
        image: {{ quote .Values.prowcontrollermanager.image }}
        args:
        - --dry-run=false
        - --config-path=/etc/config/config.yaml
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-token-path=/etc/github/oauth
        - --enable-controller=plank
        - --job-config-path=/etc/job-config
        ports:
          - name: metrics
            containerPort: 9090
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: {{ .Values.secrets.githubToken }}
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config