apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  type: ClusterIP
  selector:
    app: pushgateway