{{ if .Values.credstash.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: credstash-controller
  name: credstash-controller
  namespace: {{ .Values.credstash.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credstash-controller
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: credstash-controller
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups:
  - credstash.local
  resources:
  - credstashsecrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: credstash-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: credstash-controller
subjects:
  - kind: ServiceAccount
    name: credstash-controller
    namespace: {{ .Values.credstash.namespace }}
{{ end }}