---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: fluentd-gcp-scaler
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: fluentd-gcp-scaler