---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kube-dns-autoscaler
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns-autoscaler