apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prow
  name: prow
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http
  jobLabel: app
  namespaceSelector:
    matchNames:
    - prow
  selector:
    matchLabels:
      app: pushgateway-external
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: deck
  name: deck
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: app
  namespaceSelector:
    matchNames:
      - prow
  selector:
    matchLabels:
      app: deck
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ghproxy
  name: ghproxy
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: app
  namespaceSelector:
    matchNames:
      - prow
  selector:
    matchLabels:
      app: ghproxy
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: hook
  name: hook
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: app
  namespaceSelector:
    matchNames:
      - prow
  selector:
    matchLabels:
      app: hook
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: plank
  name: plank
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: app
  namespaceSelector:
    matchNames:
      - prow
  selector:
    matchLabels:
      app: plank
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sinker
  name: sinker
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: app
  namespaceSelector:
    matchNames:
      - prow
  selector:
    matchLabels:
      app: sinker
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tide
  name: tide
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: app
  namespaceSelector:
    matchNames:
      - prow
  selector:
    matchLabels:
      app: tide
