apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
  name: oauth2-proxy
  namespace: {{ .Values.oauthproxy.namespace }}
spec:
  rules:
  - host: {{ .Values.baseurl }}
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: http
        path: /oauth2
  tls:
    - hosts:
      - {{ .Values.baseurl }}
      secretName: prow-tls