apiVersion: credstash.local/v1
kind: CredStashSecret
metadata:
  name: github-oauth-secret
spec:
  - name: client-id
    from: {{ .Values.credstashSecrets.oauthproxy_clientid.key | quote | b64enc }}
    table: {{ .Values.credstashSecrets.oauthproxy_clientid.table | default .Values.credstashSecrets.defaultTable | quote | b64enc }}
    version: {{ .Values.credstashSecrets.oauthproxy_clientid.version | default .Values.credstashSecrets.defaultVersion | quote | b64enc}}
  - name: client-secret
    from: {{ .Values.credstashSecrets.oauthproxy_clientsecret.key | quote | b64enc }}
    table: {{ .Values.credstashSecrets.oauthproxy_clientsecret.table | default .Values.credstashSecrets.defaultTable | quote | b64enc }}
    version: {{ .Values.credstashSecrets.oauthproxy_clientsecret.version | default .Values.credstashSecrets.defaultVersion | quote | b64enc }}
  - name: cookie-secret
    from: {{ .Values.credstashSecrets.oauthproxy_cookiesecret.key | quote | b64enc }}
    table: {{ .Values.credstashSecrets.oauthproxy_cookiesecret.table | default .Values.credstashSecrets.defaultTable | quote | b64enc }}
    version: {{ .Values.credstashSecrets.oauthproxy_cookiesecret.version | default .Values.credstashSecrets.defaultVersion | quote | b64enc }}    
# apiVersion: v1
# kind: Secret
# metadata:
#   name: github-oauth-secret
# type: Opaque
# data:
#   client-id: 
#   client-secret: 
#   cookie-secret:  