apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-secret
  namespace: {{ .Values.oauthproxy.namespace }}
type: Opaque
data:
  client-id: {{ .Values.secrets.oauthproxy.clientid }}
  client-secret: {{ .Values.secrets.oauthproxy.clientsecret }}
  cookie-secret:  {{ randAlphaNum 20 | b64enc | quote }} 