apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: {{ .Values.oauthproxy.namespace }}
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: http
    port: 80
  selector:
    k8s-app: oauth2-proxy