dependencies:
  - name: external-dns
    version: 2.9.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    tags:
      - external-dns 
  - name: cert-manager
    version: v0.11.0
    repository:  https://charts.jetstack.io/
    tags:
      - cert-manager
  - name: nginx-ingress
    version: 1.24.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    tags:
      - nginx-ingress